apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_addr = 0.0.0.0
    http_port = 3000
    [analytics]
    check_for_updates = false
    [plugins]
    enable_alpha = true
    [security]
    admin_user = Inteliverse
    admin_password = sW&Xxq1b47B8
    allow_embedding = true
    [auth.anonymous]
    enabled = true
    [auth.basic]
    enabled = false
    [auth.ldap]
    enabled = false
    [users]
    viewers_can_edit = true
    allow_org_create = true
    auto_assign_org_role = Admin
    default_theme = light
