apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-webapp
  labels:
    app: intel
spec:
  replicas: 1
  selector:
    matchLabels:
      service: intel-webapp
  template:
    metadata:
      labels:
        app: intel
        service: intel-webapp
    spec:
      hostNetwork: true
      containers:
        - name: webapp
          image: 878426398556.dkr.ecr.ap-south-1.amazonaws.com/argocd:webapp1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
      imagePullSecrets:
        - name: ecr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: intel-webapp
  labels:
    app: intel
    service: intel-webapp
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: intel
    service: intel-webapp
