apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-webapi
  labels:
    app: intel
spec:
  replicas: 1
  selector:
    matchLabels:
      service: intel-webapi
  template:
    metadata:
      labels:
        app: intel
        service: intel-webapi
    spec:
      hostNetwork: true
      containers:
        - name: webapi
          image: 435218030946.dkr.ecr.us-east-2.amazonaws.com/argocd:webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5001
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
      imagePullSecrets:
        - name: ecr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: intel-webapi
  labels:
    app: intel
    service: intel-webapi
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      
      nodePort: 30010
  selector:
    service: intel-webapi
